services:
  dev:
    build:
      context: .
      dockerfile: docker/fail_safe-dev/Dockerfile
    tty: true
    env_file:
      - ./envfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
    networks:
      - net
    volumes:
      - '.:/home/app/fail_safe'
volumes:
  .:
networks:
  net:
