name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: --release -o dist --find-interpreter
    - name: Pip install
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"

    # Pytest block
    - name: Install pytest
      run: |
        python -m pip install pytest
    - name: Run pytest
      run: |
        python -m pytest

    # Shinx block
    # - name: Install Cargo Sphinx
    #   run: |
    #     cargo install cargo-sphinx
    - name: Build HTML
      # uses: ammaraskar/sphinx-action@master
      run: |
        cd docs; make html -e; cd ..
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
